version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
